import {
  BarChart3,
  Bot,
  Building2,
  Camera,
  Cpu,
  Globe2,
  Lightbulb,
  Megaphone,
  MonitorSmartphone,
  PartyPopper,
  PenTool,
  Server,
  Smartphone,
  Sparkles,
  TrendingUp,
  Users,
  Wrench,
  type LucideProps,
} from "lucide-react";
import type { ComponentType } from "react";
import type { ServiceSlug } from "@/lib/constants";

export const SERVICE_ICONS = {
  branding: PenTool,
  "digital-strategy": TrendingUp,
  "social-media-marketing": Megaphone,
  "content-marketing": Sparkles,
  "email-sms-marketing": Smartphone,
  "experiential-marketing": Users,
  "billboard-led-advertising": Building2,
  "web-development": MonitorSmartphone,
  "custom-software": BarChart3,
  "ai-automation": Bot,
  "seo-geo-aeo": Globe2,
  "data-analytics": BarChart3,
  "it-consulting": Lightbulb,
  "network-systems": Server,
  cctv: Camera,
  iot: Cpu,
  "it-maintenance": Wrench,
  "it-consultancy": Lightbulb,
  "e-invitations": PartyPopper,
} as const satisfies Record<ServiceSlug, ComponentType<LucideProps>>;